import { assets } from '../bandAssets'

// Generated by scripts/gen_band.py — do not hand-edit.
// Figma Frame 244 (2695:163) band "akad": y 3958..4946, height 988 design px.
// x/y are band-local design px; `z` is the GLOBAL Figma child order, so layers still
// stack correctly against the bands above and below this one.
//
// Positions are NOT Figma's reported bounds — see "exported bounds are not node bounds"
// in SLICING.md. Regenerate rather than nudging numbers by hand.
import type { BandLayer } from '../bandLayer'

export const BAND_TOP = 3958
export const BAND_HEIGHT = 988

export const LAYERS: BandLayer[] = [
  { z: 11, id: '2706:140', src: assets['akad/parts/2706-140.webp'], x: 0, y: 611, w: 375, h: 474 },
  { z: 14, id: '2706:135', src: assets['akad/parts/2706-135.webp'], x: 0, y: 288, w: 375, h: 616 },
  { z: 126, id: '2706:129', src: assets['akad/parts/2706-129.webp'], x: 0, y: 0, w: 375, h: 933 },
  { z: 128, id: '2706:130', src: assets['akad/parts/2706-130.webp'], x: 0, y: 697, w: 223, h: 272 },
  { z: 130, id: '2706:131', src: assets['resepsi/parts/2712-157.webp'], x: 150, y: 697, w: 225, h: 272 },
  { z: 133, id: '2706:144', src: assets['akad/parts/2706-144.webp'], x: 0, y: 810, w: 375, h: 168 },
  { z: 137, id: '2706:143', src: assets['akad/parts/2706-143.webp'], x: 63, y: 751, w: 249, h: 176 },
  { z: 141, id: '2712:128', src: assets['akad/parts/2712-128.webp'], x: 31, y: 104, w: 70, h: 190 },
  { z: 143, id: '2706:151', src: assets['akad/parts/2706-151.webp'], x: 227, y: 99, w: 76, h: 117 },
  { z: 145, id: '2706:152', src: assets['resepsi/parts/2712-165.webp'], x: 48, y: 149, w: 76, h: 117 },
  { z: 147, id: '2706:153', src: assets['akad/parts/2706-153.webp'], x: 363, y: 166, w: 77, h: 115 },
  { z: 149, id: '2706:154', src: assets['akad/parts/2706-154.webp'], x: 0, y: 193, w: 55, h: 115 },
  { z: 151, id: '2706:157', src: assets['akad/parts/2706-157.webp'], x: 262, y: 312, w: 77, h: 115 },
  { z: 153, id: '2706:155', src: assets['akad/parts/2706-155.webp'], x: 0, y: 251, w: 103, h: 264 },
  { z: 155, id: '2706:156', src: assets['akad/parts/2706-156.webp'], x: 262, y: 216, w: 78, h: 191 },
  { z: 167, id: '2706:163', src: assets['akad/parts/2706-163.webp'], x: 158, y: 697, w: 59, h: 24 },
  { z: 171, id: '2712:127', src: assets['akad/parts/2712-127.webp'], x: 62, y: 231, w: 47, h: 47 },
]
