import { assets } from '../bandAssets'

// Generated by scripts/gen_band.py — do not hand-edit.
// Figma Frame 244 (2695:163) band "bride": y 2249..3046, height 797 design px.
// x/y are band-local design px; `z` is the GLOBAL Figma child order, so layers still
// stack correctly against the bands above and below this one.
//
// Positions are NOT Figma's reported bounds — see "exported bounds are not node bounds"
// in SLICING.md. Regenerate rather than nudging numbers by hand.
import type { BandLayer } from '../bandLayer'

export const BAND_TOP = 2249
export const BAND_HEIGHT = 797

export const LAYERS: BandLayer[] = [
  { z: 18, id: '2699:245', src: assets['bride/parts/2699-245.webp'], x: 0, y: 0, w: 375, h: 373 },
  { z: 20, id: '2699:246', src: assets['bride/parts/2699-246.webp'], x: 0, y: 220, w: 375, h: 321 },
  { z: 51, id: '2699:248', src: assets['bride/parts/2699-248.webp'], x: 0, y: 380, w: 375, h: 430 },
  { z: 53, id: '2699:249', src: assets['bride/parts/2699-249.webp'], x: 0, y: 484, w: 375, h: 375 },
  { z: 55, id: '2699:250', src: assets['bride/parts/2699-250.webp'], x: 0, y: 485, w: 375, h: 375 },
  { z: 58, id: '2699:251', src: assets['bride/parts/2699-251.webp'], x: 88, y: 210, w: 200, h: 295 },
  { z: 60, id: '2699:252', src: assets['groom/parts/2699-227.webp'], x: 97, y: 519, w: 151, h: 202 },
  { z: 62, id: '2699:253', src: assets['groom/parts/2699-229.webp'], x: 295, y: 509, w: 146, h: 139 },
  { z: 64, id: '2699:254', src: assets['bride/parts/2699-254.webp'], x: 0, y: 84, w: 375, h: 521 },
  { z: 66, id: '2699:255', src: assets['groom/parts/2699-222.webp'], x: 33, y: 250, w: 34, h: 130 },
  { z: 70, id: '2699:257', src: assets['groom/parts/2699-241.webp'], x: 291, y: 471, w: 142, h: 133 },
  { z: 72, id: '2699:258', src: assets['groom/parts/2699-239.webp'], x: 326, y: 383, w: 85, h: 135 },
  { z: 74, id: '2699:259', src: assets['groom/parts/2699-224.webp'], x: 22, y: 305, w: 45, h: 45 },
  { z: 76, id: '2699:260', src: assets['groom/parts/2699-235.webp'], x: 94, y: 465, w: 80, h: 80 },
  { z: 78, id: '2699:261', src: assets['groom/parts/2699-235.webp'], x: 195, y: 465, w: 80, h: 80 },
  { z: 80, id: '2699:262', src: assets['groom/parts/2699-225.webp'], x: 10, y: 398, w: 80, h: 80 },
  { z: 82, id: '2699:263', src: assets['groom/parts/2699-234.webp'], x: 154, y: 492, w: 62, h: 62 },
  { z: 84, id: '2699:264', src: assets['bride/parts/2699-264.webp'], x: -17, y: 315, w: 97, h: 129 },
  { z: 86, id: '2699:265', src: assets['bride/parts/2699-265.webp'], x: 0, y: 305, w: 86, h: 268 },
  { z: 88, id: '2699:266', src: assets['bride/parts/2699-266.webp'], x: 289, y: 305, w: 86, h: 268 },
  { z: 90, id: '2699:267', src: assets['bride/parts/2699-267.webp'], x: 0, y: 451, w: 69, h: 165 },
  { z: 92, id: '2699:268', src: assets['bride/parts/2699-268.webp'], x: 295, y: 451, w: 80, h: 165 },
  { z: 94, id: '2699:269', src: assets['groom/parts/2699-226.webp'], x: 190, y: 90, w: 124, h: 137 },
  { z: 96, id: '2699:270', src: assets['groom/parts/2699-220.webp'], x: 266, y: 168, w: 82, h: 201 },
  { z: 98, id: '2699:271', src: assets['groom/parts/2699-221.webp'], x: 252, y: 159, w: 55, h: 55 },
  { z: 100, id: '2699:272', src: assets['groom/parts/2699-231.webp'], x: 185, y: 438, w: 139, h: 149 },
  { z: 101, id: '2699:296', src: assets['bride/parts/2699-296.webp'], x: 0, y: 478, w: 375, h: 433 },
  { z: 103, id: '2699:273', src: assets['groom/parts/2699-232.webp'], x: 46, y: 438, w: 139, h: 149 },
  { z: 105, id: '2699:274', src: assets['bride/parts/2699-274.webp'], x: 0, y: 599, w: 375, h: 582 },
]
