import { assets } from '../bandAssets'

// Generated by scripts/gen_band.py — do not hand-edit.
// Figma Frame 244 (2695:163) band "countdown": y 3046..3746, height 700 design px.
// x/y are band-local design px; `z` is the GLOBAL Figma child order, so layers still
// stack correctly against the bands above and below this one.
//
// Positions are NOT Figma's reported bounds — see "exported bounds are not node bounds"
// in SLICING.md. Regenerate rather than nudging numbers by hand.
import type { BandLayer } from '../bandLayer'

export const BAND_TOP = 3046
export const BAND_HEIGHT = 700

export const LAYERS: BandLayer[] = [
  { z: 16, id: '2699:281', src: assets['countdown/parts/2699-281.webp'], x: 0, y: 35, w: 375, h: 626 },
  { z: 110, id: '2699:277', src: assets['countdown/parts/2699-277.webp'], x: 0, y: 357, w: 375, h: 237 },
  { z: 111, id: '2699:280', src: assets['countdown/parts/2699-280.webp'], x: 76, y: 234, w: 227, h: 355 },
  { z: 112, id: '2699:279', src: assets['countdown/parts/2699-279.webp'], x: 1, y: 157, w: 374, h: 504 },
  { z: 113, id: '2699:278', src: assets['countdown/parts/2699-278.webp'], x: 0, y: 451, w: 375, h: 199 },
  { z: 117, id: '2699:283', src: assets['countdown/parts/2699-283.webp'], x: 116, y: 284, w: 155, h: 210 },
  { z: 216, id: '2712:343', src: assets['countdown/parts/2712-343.webp'], x: 263, y: 442, w: 112, h: 177 },
  { z: 225, id: '2738:126', src: assets['countdown/parts/2738-126.webp'], x: 72, y: 0, w: 245, h: 13 },
]
