import { assets } from '../bandAssets'

// Generated by scripts/gen_band.py — do not hand-edit.
// Figma Frame 244 (2695:163) band "footer": y 9053..9866, height 813 design px.
// x/y are band-local design px; `z` is the GLOBAL Figma child order, so layers still
// stack correctly against the bands above and below this one.
//
// Positions are NOT Figma's reported bounds — see "exported bounds are not node bounds"
// in SLICING.md. Regenerate rather than nudging numbers by hand.
import type { BandLayer } from '../bandLayer'

export const BAND_TOP = 9053
export const BAND_HEIGHT = 813

export const LAYERS: BandLayer[] = [
  { z: 196, id: '2712:317', src: assets['footer/parts/2712-317.webp'], x: 0, y: 68, w: 375, h: 513 },
  { z: 198, id: '2712:318', src: assets['footer/parts/2712-318.webp'], x: 0, y: 448, w: 375, h: 294 },
  { z: 199, id: '2712:319', src: assets['footer/parts/2712-319.webp'], x: 84, y: 505, w: 207, h: 151 },
  { z: 200, id: '2712:320', src: assets['footer/parts/2712-320.webp'], x: 0, y: 144, w: 375, h: 593 },
  { z: 204, id: '2712:325', src: assets['footer/parts/2712-325.webp'], x: 0, y: 784, w: 375, h: 28 },
  { z: 206, id: '2712:327', src: assets['footer/parts/2712-327.webp'], x: 0, y: 474, w: 375, h: 311 },
  { z: 207, id: '2712:328', src: assets['footer/parts/2712-328.webp'], x: 136, y: 272, w: 103, h: 127 },
  { z: 208, id: '2712:337', src: assets['footer/parts/2712-337.webp'], x: 284, y: 477, w: 91, h: 204 },
  { z: 209, id: '2712:338', src: assets['footer/parts/2712-338.webp'], x: 0, y: 479, w: 104, h: 204 },
  { z: 210, id: '2712:339', src: assets['footer/parts/2712-339.webp'], x: 0, y: 621, w: 375, h: 165 },
  { z: 217, id: '2712:346', src: assets['footer/parts/2712-346.webp'], x: 239, y: 234, w: 117, h: 117 },
  { z: 220, id: '2712:350', src: assets['footer/parts/2712-350.webp'], x: 190, y: 621, w: 185, h: 153 },
  { z: 221, id: '2712:351', src: assets['footer/parts/2712-351.webp'], x: 44, y: 699, w: 79, h: 69 },
]
