import { assets } from '../bandAssets'

// Generated by scripts/gen_band.py — do not hand-edit.
// Figma Frame 244 (2695:163) band "gallery": y 8414..9053, height 639 design px.
// x/y are band-local design px; `z` is the GLOBAL Figma child order, so layers still
// stack correctly against the bands above and below this one.
//
// Positions are NOT Figma's reported bounds — see "exported bounds are not node bounds"
// in SLICING.md. Regenerate rather than nudging numbers by hand.
import type { BandLayer } from '../bandLayer'

export const BAND_TOP = 8414
export const BAND_HEIGHT = 639

export const LAYERS: BandLayer[] = [
  { z: 2, id: '2712:332', src: assets['gallery/parts/2712-332.webp'], x: 205, y: 478, w: 170, h: 335 },
  { z: 3, id: '2712:333', src: assets['gallery/parts/2712-333.webp'], x: 200, y: 477, w: 175, h: 335 },
  { z: 4, id: '2712:334', src: assets['gallery/parts/2712-334.webp'], x: 0, y: 423, w: 142, h: 210 },
  { z: 5, id: '2712:335', src: assets['gallery/parts/2712-334.webp'], x: 161, y: 423, w: 142, h: 210 },
  { z: 6, id: '2712:336', src: assets['gallery/parts/2712-334.webp'], x: 80, y: 423, w: 142, h: 210 },
  { z: 7, id: '2712:313', src: assets['gallery/parts/2712-313.webp'], x: 0, y: 343, w: 375, h: 369 },
  { z: 10, id: '2712:308', src: assets['gallery/parts/2712-308.webp'], x: 0, y: 256, w: 375, h: 215 },
  { z: 188, id: '2712:279', src: assets['gallery/parts/2712-279.webp'], x: 3, y: 70, w: 371, h: 384 },
  { z: 192, id: '2712:305', src: assets['gallery/parts/2712-305.webp'], x: 0, y: 288, w: 86, h: 190 },
  { z: 193, id: '2712:306', src: assets['gallery/parts/2712-306.webp'], x: 290, y: 288, w: 85, h: 190 },
  { z: 194, id: '2712:314', src: assets['gallery/parts/2712-314.webp'], x: 0, y: 0, w: 86, h: 205 },
  { z: 215, id: '2712:342', src: assets['gallery/parts/2712-342.webp'], x: 0, y: 39, w: 104, h: 178 },
  { z: 218, id: '2712:348', src: assets['gallery/parts/2712-348.webp'], x: 71, y: 417, w: 101, h: 88 },
]
