import { assets } from '../bandAssets'

// Generated by scripts/gen_band.py — do not hand-edit.
// Figma Frame 244 (2695:163) band "gift": y 6021..6967, height 946 design px.
// x/y are band-local design px; `z` is the GLOBAL Figma child order, so layers still
// stack correctly against the bands above and below this one.
//
// Positions are NOT Figma's reported bounds — see "exported bounds are not node bounds"
// in SLICING.md. Regenerate rather than nudging numbers by hand.
import type { BandLayer } from '../bandLayer'

export const BAND_TOP = 6021
export const BAND_HEIGHT = 946

export const LAYERS: BandLayer[] = [
  { z: 1, id: '2713:133', src: assets['gift/parts/2713-133.webp'], x: 0, y: 659, w: 375, h: 644 },
  { z: 175, id: '2712:209', src: assets['gift/parts/2712-209.webp'], x: 160, y: 166, w: 21, h: 21 },
  { z: 176, id: '2712:210', src: assets['gift/parts/2712-209.webp'], x: 160, y: 287, w: 21, h: 21 },
  { z: 177, id: '2712:211', src: assets['gift/parts/2712-209.webp'], x: 160, y: 471, w: 21, h: 21 },
  { z: 178, id: '2712:212', src: assets['gift/parts/2712-212.webp'], x: 0, y: 546, w: 98, h: 279 },
  { z: 179, id: '2712:213', src: assets['gift/parts/2712-213.webp'], x: 277, y: 548, w: 98, h: 279 },
  { z: 180, id: '2712:214', src: assets['gift/parts/2712-214.webp'], x: 0, y: 721, w: 55, h: 125 },
  { z: 181, id: '2712:215', src: assets['gift/parts/2712-215.webp'], x: 320, y: 721, w: 55, h: 125 },
  { z: 182, id: '2712:217', src: assets['gift/parts/2712-217.webp'], x: 182, y: 721, w: 193, h: 263 },
  { z: 183, id: '2712:219', src: assets['gift/parts/2712-219.webp'], x: 187, y: 721, w: 188, h: 263 },
  { z: 219, id: '2712:349', src: assets['gift/parts/2712-349.webp'], x: 105, y: 752, w: 194, h: 157 },
]
