import { assets } from '../bandAssets'

// Generated by scripts/gen_band.py — do not hand-edit.
// Figma Frame 244 (2695:163) band "groom": y 1342..2158, height 816 design px.
// x/y are band-local design px; `z` is the GLOBAL Figma child order, so layers still
// stack correctly against the bands above and below this one.
//
// Positions are NOT Figma's reported bounds — see "exported bounds are not node bounds"
// in SLICING.md. Regenerate rather than nudging numbers by hand.
import type { BandLayer } from '../bandLayer'

export const BAND_TOP = 1342
export const BAND_HEIGHT = 816

export const LAYERS: BandLayer[] = [
  { z: 17, id: '2699:213', src: assets['groom/parts/2699-213.webp'], x: 0, y: 0, w: 375, h: 373 },
  { z: 19, id: '2699:210', src: assets['groom/parts/2699-210.webp'], x: 0, y: 220, w: 375, h: 321 },
  { z: 50, id: '2699:206', src: assets['groom/parts/2699-206.webp'], x: 0, y: 380, w: 375, h: 430 },
  { z: 52, id: '2699:207', src: assets['groom/parts/2699-207.webp'], x: 0, y: 298, w: 375, h: 375 },
  { z: 54, id: '2699:208', src: assets['groom/parts/2699-208.webp'], x: 0, y: 298, w: 375, h: 375 },
  { z: 57, id: '2699:211', src: assets['groom/parts/2699-211.webp'], x: 70, y: 222, w: 235, h: 283 },
  { z: 59, id: '2699:227', src: assets['groom/parts/2699-227.webp'], x: 100, y: 519, w: 151, h: 202 },
  { z: 61, id: '2699:229', src: assets['groom/parts/2699-229.webp'], x: 298, y: 509, w: 146, h: 139 },
  { z: 63, id: '2699:212', src: assets['groom/parts/2699-212.webp'], x: 0, y: 84, w: 375, h: 521 },
  { z: 65, id: '2699:222', src: assets['groom/parts/2699-222.webp'], x: 36, y: 250, w: 34, h: 130 },
  { z: 69, id: '2699:241', src: assets['groom/parts/2699-241.webp'], x: 294, y: 471, w: 142, h: 133 },
  { z: 71, id: '2699:239', src: assets['groom/parts/2699-239.webp'], x: 329, y: 383, w: 85, h: 135 },
  { z: 73, id: '2699:224', src: assets['groom/parts/2699-224.webp'], x: 25, y: 305, w: 45, h: 45 },
  { z: 75, id: '2699:235', src: assets['groom/parts/2699-235.webp'], x: 97, y: 465, w: 80, h: 80 },
  { z: 77, id: '2699:236', src: assets['groom/parts/2699-235.webp'], x: 198, y: 465, w: 80, h: 80 },
  { z: 79, id: '2699:225', src: assets['groom/parts/2699-225.webp'], x: 13, y: 398, w: 80, h: 80 },
  { z: 81, id: '2699:234', src: assets['groom/parts/2699-234.webp'], x: 157, y: 492, w: 62, h: 62 },
  { z: 83, id: '2699:219', src: assets['groom/parts/2699-219.webp'], x: -16, y: 315, w: 100, h: 129 },
  { z: 85, id: '2699:215', src: assets['groom/parts/2699-215.webp'], x: 0, y: 305, w: 89, h: 268 },
  { z: 87, id: '2699:216', src: assets['groom/parts/2699-216.webp'], x: 292, y: 305, w: 83, h: 268 },
  { z: 89, id: '2699:217', src: assets['groom/parts/2699-217.webp'], x: 0, y: 451, w: 72, h: 165 },
  { z: 91, id: '2699:218', src: assets['groom/parts/2699-218.webp'], x: 298, y: 451, w: 77, h: 165 },
  { z: 93, id: '2699:226', src: assets['groom/parts/2699-226.webp'], x: 193, y: 90, w: 124, h: 137 },
  { z: 95, id: '2699:220', src: assets['groom/parts/2699-220.webp'], x: 269, y: 168, w: 82, h: 201 },
  { z: 97, id: '2699:221', src: assets['groom/parts/2699-221.webp'], x: 255, y: 159, w: 55, h: 55 },
  { z: 99, id: '2699:231', src: assets['groom/parts/2699-231.webp'], x: 188, y: 438, w: 139, h: 149 },
  { z: 102, id: '2699:232', src: assets['groom/parts/2699-232.webp'], x: 49, y: 438, w: 139, h: 149 },
  { z: 104, id: '2699:243', src: assets['groom/parts/2699-243.webp'], x: 0, y: 460, w: 375, h: 582 },
  { z: 119, id: '2699:290', src: assets['groom/parts/2699-290.webp'], x: 0, y: 675, w: 51, h: 313 },
  { z: 120, id: '2699:291', src: assets['groom/parts/2699-291.webp'], x: 323, y: 675, w: 52, h: 313 },
  { z: 121, id: '2713:145', src: assets['groom/parts/2713-145.webp'], x: 260, y: 806, w: 93, h: 116 },
  { z: 122, id: '2699:292', src: assets['groom/parts/2699-292.webp'], x: 238, y: 721, w: 137, h: 216 },
  { z: 123, id: '2699:293', src: assets['groom/parts/2699-293.webp'], x: 0, y: 721, w: 154, h: 216 },
  { z: 124, id: '2699:294', src: assets['groom/parts/2699-294.webp'], x: 0, y: 712, w: 92, h: 174 },
  { z: 125, id: '2699:295', src: assets['groom/parts/2699-295.webp'], x: 288, y: 712, w: 87, h: 174 },
]
