import { assets } from '../bandAssets'

// Generated by scripts/gen_band.py — do not hand-edit.
// Figma Frame 244 (2695:163) band "hero": y 0..709, height 709 design px.
// x/y are band-local design px; `z` is the GLOBAL Figma child order, so layers still
// stack correctly against the bands above and below this one.
//
// Positions are NOT Figma's reported bounds — see "exported bounds are not node bounds"
// in SLICING.md. Regenerate rather than nudging numbers by hand.
import type { BandLayer } from '../bandLayer'

export const BAND_TOP = 0
export const BAND_HEIGHT = 709

export const LAYERS: BandLayer[] = [
  { z: 13, id: '2695:178', src: assets['hero/parts/2695-178.webp'], x: 0, y: 618, w: 144, h: 160 },
  { z: 21, id: '2695:165', src: assets['hero/parts/2695-165.webp'], x: 0, y: 0, w: 375, h: 691 },
  { z: 22, id: '2695:166', src: assets['hero/parts/2695-166.webp'], x: 0, y: 11, w: 375, h: 669 },
  { z: 23, id: '2695:173', src: assets['hero/parts/2695-173.webp'], x: 60, y: 272, w: 266, h: 273 },
  { z: 25, id: '2695:172', src: assets['hero/parts/2695-172.webp'], x: 34, y: 197, w: 307, h: 402 },
  { z: 28, id: '2695:179', src: assets['hero/parts/2695-179.webp'], x: 0, y: 428, w: 375, h: 263 },
  { z: 29, id: '2695:174', src: assets['hero/parts/2695-174.webp'], x: 334, y: 161, w: 41, h: 210 },
  { z: 30, id: '2695:175', src: assets['hero/parts/2695-175.webp'], x: 0, y: 161, w: 41, h: 210 },
  { z: 31, id: '2695:176', src: assets['hero/parts/2695-176.webp'], x: 0, y: 301, w: 144, h: 397 },
  { z: 32, id: '2695:177', src: assets['hero/parts/2695-177.webp'], x: 231, y: 294, w: 144, h: 397 },
  { z: 33, id: '2695:183', src: assets['hero/parts/2695-183.webp'], x: 0, y: 580, w: 53, h: 107 },
  { z: 34, id: '2695:184', src: assets['hero/parts/2695-184.webp'], x: 322, y: 580, w: 53, h: 107 },
  { z: 35, id: '2695:180', src: assets['hero/parts/2695-180.webp'], x: 176, y: 618, w: 199, h: 149 },
  { z: 36, id: '2695:181', src: assets['hero/parts/2695-181.webp'], x: 0, y: 617, w: 197, h: 149 },
  { z: 37, id: '2695:189', src: assets['hero/parts/2695-189.webp'], x: 10, y: 518, w: 179, h: 224 },
  { z: 38, id: '2695:190', src: assets['hero/parts/2695-189.webp'], x: 189, y: 518, w: 179, h: 224 },
  { z: 39, id: '2695:182', src: assets['hero/parts/2695-182.webp'], x: 0, y: 562, w: 375, h: 516 },
  { z: 40, id: '2695:194', src: assets['hero/parts/2695-194.webp'], x: 318, y: 579, w: 34, h: 114 },
  { z: 41, id: '2695:195', src: assets['hero/parts/2695-195.webp'], x: 0, y: 485, w: 34, h: 114 },
  { z: 48, id: '2697:202', src: assets['hero/parts/2697-202.webp'], x: 326, y: 682, w: 49, h: 183 },
]
