import { assets } from '../bandAssets'

// Generated by scripts/gen_band.py — do not hand-edit.
// Figma Frame 244 (2695:163) band "quote": y 709..1251, height 542 design px.
// x/y are band-local design px; `z` is the GLOBAL Figma child order, so layers still
// stack correctly against the bands above and below this one.
//
// Positions are NOT Figma's reported bounds — see "exported bounds are not node bounds"
// in SLICING.md. Regenerate rather than nudging numbers by hand.
import type { BandLayer } from '../bandLayer'

export const BAND_TOP = 709
export const BAND_HEIGHT = 542

export const LAYERS: BandLayer[] = [
  { z: 42, id: '2695:196', src: assets['quote/parts/2695-196.webp'], x: 0, y: 0, w: 375, h: 440 },
  { z: 43, id: '2696:198', src: assets['quote/parts/2696-198.webp'], x: 0, y: 248, w: 375, h: 213 },
  { z: 44, id: '2696:197', src: assets['quote/parts/2696-197.webp'], x: 5, y: 327, w: 370, h: 226 },
  { z: 45, id: '2697:199', src: assets['quote/parts/2697-199.webp'], x: 130, y: 127, w: 245, h: 341 },
  { z: 49, id: '2697:204', src: assets['quote/parts/2697-204.webp'], x: 58, y: 308, w: 105, h: 132 },
  { z: 223, id: '2713:143', src: assets['quote/parts/2713-143.webp'], x: 0, y: 374, w: 104, h: 153 },
]
