import { assets } from '../bandAssets'

// Generated by scripts/gen_band.py — do not hand-edit.
// Figma Frame 244 (2695:163) band "resepsi": y 4946..6021, height 1075 design px.
// x/y are band-local design px; `z` is the GLOBAL Figma child order, so layers still
// stack correctly against the bands above and below this one.
//
// Positions are NOT Figma's reported bounds — see "exported bounds are not node bounds"
// in SLICING.md. Regenerate rather than nudging numbers by hand.
import type { BandLayer } from '../bandLayer'

export const BAND_TOP = 4946
export const BAND_HEIGHT = 1075

export const LAYERS: BandLayer[] = [
  { z: 12, id: '2712:149', src: assets['resepsi/parts/2712-149.webp'], x: 0, y: 611, w: 375, h: 474 },
  { z: 15, id: '2712:150', src: assets['resepsi/parts/2712-150.webp'], x: 0, y: 288, w: 375, h: 616 },
  { z: 127, id: '2712:156', src: assets['resepsi/parts/2712-156.webp'], x: 0, y: 0, w: 375, h: 933 },
  { z: 129, id: '2712:157', src: assets['resepsi/parts/2712-157.webp'], x: 150, y: 697, w: 225, h: 272 },
  { z: 131, id: '2712:158', src: assets['akad/parts/2706-130.webp'], x: 0, y: 697, w: 223, h: 272 },
  { z: 134, id: '2712:160', src: assets['resepsi/parts/2712-160.webp'], x: 0, y: 810, w: 375, h: 168 },
  { z: 135, id: '2706:145', src: assets['resepsi/parts/2706-145.webp'], x: 0, y: 14, w: 375, h: 168 },
  { z: 136, id: '2712:161', src: assets['resepsi/parts/2712-161.webp'], x: 0, y: 1002, w: 375, h: 168 },
  { z: 138, id: '2712:162', src: assets['resepsi/parts/2712-162.webp'], x: 310, y: 751, w: 249, h: 176 },
  { z: 142, id: '2712:164', src: assets['resepsi/parts/2712-164.webp'], x: 272, y: 104, w: 70, h: 190 },
  { z: 144, id: '2712:165', src: assets['resepsi/parts/2712-165.webp'], x: 70, y: 99, w: 76, h: 117 },
  { z: 146, id: '2712:166', src: assets['akad/parts/2706-151.webp'], x: 249, y: 149, w: 76, h: 117 },
  { z: 148, id: '2712:167', src: assets['resepsi/parts/2712-167.webp'], x: 10, y: 166, w: 77, h: 115 },
  { z: 150, id: '2712:168', src: assets['resepsi/parts/2712-168.webp'], x: 318, y: 193, w: 57, h: 115 },
  { z: 152, id: '2712:169', src: assets['resepsi/parts/2712-169.webp'], x: 111, y: 312, w: 77, h: 115 },
  { z: 154, id: '2712:170', src: assets['resepsi/parts/2712-170.webp'], x: 270, y: 251, w: 105, h: 264 },
  { z: 156, id: '2712:171', src: assets['resepsi/parts/2712-171.webp'], x: 33, y: 216, w: 78, h: 191 },
  { z: 168, id: '2712:177', src: assets['akad/parts/2706-163.webp'], x: 156, y: 697, w: 59, h: 24 },
  { z: 172, id: '2712:179', src: assets['resepsi/parts/2712-179.webp'], x: 264, y: 231, w: 47, h: 47 },
]
