import { assets } from '../bandAssets'

// Generated by scripts/gen_band.py — do not hand-edit.
// Figma Frame 244 (2695:163) band "rsvp": y 6967..7496, height 529 design px.
// x/y are band-local design px; `z` is the GLOBAL Figma child order, so layers still
// stack correctly against the bands above and below this one.
//
// Positions are NOT Figma's reported bounds — see "exported bounds are not node bounds"
// in SLICING.md. Regenerate rather than nudging numbers by hand.
import type { BandLayer } from '../bandLayer'

export const BAND_TOP = 6967
export const BAND_HEIGHT = 529

export const LAYERS: BandLayer[] = [
  { z: 189, id: '2712:303', src: assets['rsvp/parts/2712-303.webp'], x: 226, y: 363, w: 149, h: 198 },
]
