import { assets } from '../bandAssets'

// Generated by scripts/gen_band.py — do not hand-edit.
// Figma Frame 244 (2695:163) band "theday": y 3746..3958, height 212 design px.
// x/y are band-local design px; `z` is the GLOBAL Figma child order, so layers still
// stack correctly against the bands above and below this one.
//
// Positions are NOT Figma's reported bounds — see "exported bounds are not node bounds"
// in SLICING.md. Regenerate rather than nudging numbers by hand.
import type { BandLayer } from '../bandLayer'

export const BAND_TOP = 3746
export const BAND_HEIGHT = 212

export const LAYERS: BandLayer[] = [
  { z: 114, id: '2699:284', src: assets['theday/parts/2699-284.webp'], x: 0, y: -52, w: 375, h: 202 },
  { z: 132, id: '2706:142', src: assets['theday/parts/2706-142.webp'], x: 168, y: 77, w: 207, h: 329 },
  { z: 173, id: '2712:180', src: assets['theday/parts/2712-180.webp'], x: 28, y: 0, w: 146, h: 146 },
  { z: 184, id: '2712:220', src: assets['theday/parts/2712-220.webp'], x: 220, y: 152, w: 155, h: 281 },
  { z: 185, id: '2712:222', src: assets['theday/parts/2712-222.webp'], x: 139, y: 195, w: 186, h: 232 },
]
