import { assets } from '../bandAssets'

// Generated by scripts/gen_band.py — do not hand-edit.
// Figma Frame 244 (2695:163) band "wish": y 7496..8414, height 918 design px.
// x/y are band-local design px; `z` is the GLOBAL Figma child order, so layers still
// stack correctly against the bands above and below this one.
//
// Positions are NOT Figma's reported bounds — see "exported bounds are not node bounds"
// in SLICING.md. Regenerate rather than nudging numbers by hand.
import type { BandLayer } from '../bandLayer'

export const BAND_TOP = 7496
export const BAND_HEIGHT = 918

export const LAYERS: BandLayer[] = [
  { z: 8, id: '2712:309', src: assets['wish/parts/2712-309.webp'], x: 0, y: 862, w: 134, h: 462 },
  { z: 9, id: '2712:310', src: assets['wish/parts/2712-310.webp'], x: 230, y: 862, w: 145, h: 462 },
  { z: 195, id: '2712:315', src: assets['wish/parts/2712-315.webp'], x: 242, y: 795, w: 133, h: 246 },
  { z: 197, id: '2729:131', src: assets['wish/parts/2729-131.webp'], x: 0, y: 696, w: 205, h: 246 },
  { z: 211, id: '2712:341', src: assets['wish/parts/2712-341.webp'], x: 268, y: 819, w: 107, h: 159 },
  { z: 212, id: '2729:130', src: assets['wish/parts/2729-130.webp'], x: 80, y: 782, w: 127, h: 159 },
  { z: 213, id: '2729:132', src: assets['wish/parts/2729-130.webp'], x: 0, y: 814, w: 127, h: 159 },
  { z: 214, id: '2712:355', src: assets['wish/parts/2712-355.webp'], x: 256, y: 868, w: 76, h: 95 },
  { z: 224, id: '2729:127', src: assets['wish/parts/2729-127.webp'], x: 24, y: 145, w: 327, h: 532 },
]
